# Common configuration.
Rails:
  Enabled: true
AllCops:
  # Include common Ruby source files.
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'Gemfile'
    - 'tmp/**/*'
    - 'build/**/*'

Style/IfUnlessModifier:
  MaxLineLength: 95

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Max: 95

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/**/*.rb'

Style/WhileUntilModifier:
  MaxLineLength: 95

Documentation:
  Enabled: false
